name: Build and deploy to-do web app to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install
        run: |
          npm install -g @angular/cli
          npm install

      - name: ng build
        run: |
          ng build --configuration production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./dist/to-do-web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "agreyddous-to-do"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C0EBD43FB4284A47AB0F3E3882C9FC74 }}
          package: .